version: "3.8"

services:
  web:
    image: yateshingale/myapp:latest
    ports:
      - "${APP_PORT}:5000"   # Uses .env variable
    restart: always
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

